package de.wi08e.myhome.model;

/**
 * This is a class to identify nodes (=external components). 
 * It is identified by a type, a manufacture and an id.
 * 
 * Examples for category: "enocean", "ip-camera", "cellphone", "email", ...
 * Exampled for manufacture: "generic", "simulator", "thermokon", "0x001", ...
 *  
 * If there is no known manufacture "generic" is used instead.
 * 
 * Type and manufacturer are lower case strings and therefore automatically converted.
 * 
 * Type, a manufacture and an id are not allowed to contain the character ":", because this is used as
 * delimiter for the descriptor
 * 
 * category, manufacture and id should me no longer than 50 chars.
 * 
 * @author Marek
 *
 */
public class Node {
	
	private String category;
	private String manufacturer;
	private String id;
	
	private String type = "unknown";
	
	/**
	 * Returns the type in lower case letters 
	 */
	public String getCategory() {
		return category;
	}
	
	/**
	 * Returns the manufacturer in lower case letters 
	 */
	public String getManufacturer() {
		return manufacturer;
	}
	
	/**
	 * Returns the id 
	 */
	public String getId() {
		return id;
	}
	
	/**
	 * initiates the object from type, manufacturer and id
	 * @param category Category
	 * @param manufacturer Manufacturer
	 * @param id Id
	 * @throws IllegalArgumentException Is thrown when ":" is used in the parameters or any parameter is left blank
	 */
	public Node(String category, String manufacturer, String id) {
		super();
		
		if (category.contains(":") || 
				manufacturer.contains(":") || 
				id.contains(":") || 
				category.length() == 0 ||
				manufacturer.length() == 0 ||
				id.length() == 0)
			throw new IllegalArgumentException();
		
		this.category = category.toLowerCase();
		this.manufacturer = manufacturer.toLowerCase();
		this.id = id;
	}
	
	/**
	 * initiates the object from descriptor
	 * @param descriptor Descriptor, as generated by toString()
	 * @throws IllegalArgumentException Is thrown descriptor is not valid
	 */
	/* NOT USED AT THE MOMENT
	public Node(String descriptor) {
		super();
		
		String[] elements = descriptor.split(":");
		if (elements.length != 3 ||
			elements[0].length() == 0 ||
			elements[1].length() == 0 ||
			elements[2].length() == 0) 
			throw new IllegalArgumentException();
		
		
		
		this.type = elements[1].toLowerCase();
		this.manufacturer = elements[2].toLowerCase();
		this.id = elements[3];
	}
	*/
	
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type.toLowerCase();
	}
	
	

	/**
	 * Returns the descriptor for this Node as a single string
	 */
	public String toString() {
		return category+':'+manufacturer+':'+id;
	}

	public boolean equals(Node node) {
		return (node.toString().contentEquals(toString()));
	}
	
}
